[package]
name = "golfscript-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
num = "0.4.0"
clap = { version = "3.2.4", features = ["derive"] }
